spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#          无负载均衡依赖本地测试使用
#          url-expression: "'http://'+host+':'+port"
#          url-expression: "'http://'+serviceId+':'+port"

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.sprikcngframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: TRACE
    org.springframework.cloud: trace